GET http://localhost:3000/api/

@baseUrl = http://localhost:3000
### 1. Create Task with jwt

# POST {{baseUrl}}/api/tasks
# Content-Type: application/json
# Authorization: Bearer 7d8a7f37ddf73515a2d9ba9d43e39d34fdd7a8f4183b06ee1a06a408013948f6c83e78332b571df29b946c4a50426e4594c7b4fd7f6f39eaf015289be379188c

# {
#   "title": "New Task",
#   "description": "Description for the new task",
#   "due_date": "2024-01-25"
# }
### 1. Create task without jwt 
POST {{baseUrl}}/api/tasks
Content-Type: application/json

{
  "title": "New Task",
  "description": "Description for the new task",
  "due_date": "2024-01-25"
}

### 2. Create Sub Task
POST {{baseUrl}}/api/subtasks
Content-Type: application/json

{
  "task_id": 2
}

### 3. Get All User Tasks 
GET {{baseUrl}}/api/tasks

### 4. Get All User Subtasks
GET {{baseUrl}}/api/subtasks?task_id=1


### 5. Update Task 
PUT {{baseUrl}}/api/tasks/2
Content-Type: application/json

{
  "due_date": "2024-01-30",
  "status": "DONE"
}

### 6. Update subtask 
PUT {{baseUrl}}/api/subtasks/
Content-Type: application/json

{
  "status": 1
}

### 7. Delete task 
DELETE {{baseUrl}}/api/tasks/1

### 8. Delete Subtask 
DELETE {{baseUrl}}/api/subtasks/1






