GET http://localhost:3000/api/

@baseUrl = http://localhost:3000
### 1. Create Task with jwt

POST {{baseUrl}}/api/tasks
Content-Type: application/json
Authorization: Bearer 4ad4498ea16242eda68160bba504270e15d98612a078d6f4f651ef796332bc1c45496e91fe795f9ed78c2e63ab07d38124ae1aee0e576dac6478f37f61654f4c

{
  "title": "New Task",
  "description": "Description for the new task",
  "due_date": "2024-01-25"
}
### 1. Create task without jwt 
# POST {{baseUrl}}/api/tasks
# Content-Type: application/json

# {
#   "title": " Task 1",
#   "description": "Description for the 1 task",
#   "due_date": "2024-01-25"
# }

### 2. Create Sub Task
POST {{baseUrl}}/api/subtasks
Content-Type: application/json

{
  "task_id": 2
}

### 3. Get All User Tasks 
GET {{baseUrl}}/api/tasks

### 4. Get All User Subtasks
GET {{baseUrl}}/api/subtasks?task_id=1


### 5. Update Task 
PUT {{baseUrl}}/api/tasks/2
Content-Type: application/json

{
  "due_date": "2024-01-30",
  "status": "DONE"
}

### 6. Update subtask 
PUT {{baseUrl}}/api/subtasks/
Content-Type: application/json

{
  "status": 1
}

### 7. Delete task 
DELETE {{baseUrl}}/api/tasks/1

### 8. Delete Subtask 
DELETE {{baseUrl}}/api/subtasks/1






